import React, { useState } from "react"
import { View, TouchableOpacity, Image, StyleSheet, ScrollView, ImageBackground } from "react-native"

const Cabellos = ({ onSelect }) => {
  const [colorSeleccionado, setColorSeleccionado] = useState("negro")
  const [imagenSeleccionada, setImagenSeleccionada] = useState(null)

  const imagenesPorColor = {
    negro: [
      require("../../assets/images/Cabellos/Cabello_negro_01.png"),
      require("../../assets/images/Cabellos/Cabello_negro_02.png"),
      require("../../assets/images/Cabellos/Cabello_negro_03.png"),
      require("../../assets/images/Cabellos/Cabello_negro_04.png"),
      require("../../assets/images/Cabellos/Cabello_negro_05.png"),
      require("../../assets/images/Cabellos/Cabello_negro_06.png"),
      require("../../assets/images/Cabellos/Cabello_negro_07.png"),
      require("../../assets/images/Cabellos/Cabello_negro_08.png"),
      require("../../assets/images/Cabellos/Cabello_negro_09.png"),
      require("../../assets/images/Cabellos/Cabello_negro_10.png"),
      require("../../assets/images/Cabellos/Cabello_negro_11.png"),
      require("../../assets/images/Cabellos/Cabello_negro_12.png"),
      require("../../assets/images/Cabellos/Cabello_negro_13.png"),
      require("../../assets/images/Cabellos/Cabello_negro_14.png"),
      require("../../assets/images/Cabellos/Cabello_negro_15.png"),
      require("../../assets/images/Cabellos/Cabello_negro_16.png"),
      require("../../assets/images/Cabellos/Cabello_negro_17.png"),
      require("../../assets/images/Cabellos/Cabello_negro_18.png"),
      require("../../assets/images/Cabellos/Cabello_negro_19.png"),
      require("../../assets/images/Cabellos/Cabello_negro_20.png"),
      require("../../assets/images/Cabellos/Cabello_negro_21.png"),
      require("../../assets/images/Cabellos/Cabello_negro_22.png"),
      require("../../assets/images/Cabellos/Cabello_negro_23.png"),
      require("../../assets/images/Cabellos/Cabello_negro_24.png"),
      require("../../assets/images/Cabellos/Cabello_negro_25.png"),
      require("../../assets/images/Cabellos/Cabello_negro_26.png"),
      require("../../assets/images/Cabellos/Cabello_negro_27.png"),
      require("../../assets/images/Cabellos/Cabello_negro_28.png"),
      require("../../assets/images/Cabellos/Cabello_negro_29.png"),
      require("../../assets/images/Cabellos/Cabello_negro_30.png"),
      require("../../assets/images/Cabellos/Cabello_negro_31.png"),
      require("../../assets/images/Cabellos/Cabello_negro_32.png"),
      require("../../assets/images/Cabellos/Cabello_negro_33.png"),
      require("../../assets/images/Cabellos/Cabello_negro_34.png"),
      require("../../assets/images/Cabellos/Cabello_negro_35.png"),
      require("../../assets/images/Cabellos/Cabello_negro_36.png"),
      require("../../assets/images/Cabellos/Cabello_negro_37.png"),
      require("../../assets/images/Cabellos/Cabello_negro_38.png"),
      require("../../assets/images/Cabellos/Cabello_negro_39.png"),
      require("../../assets/images/Cabellos/Cabello_negro_40.png"),
    ],
    rojo: [
      require("../../assets/images/Cabellos/Cabello_rojo_01.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_02.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_03.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_04.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_05.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_06.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_07.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_08.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_09.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_10.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_11.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_12.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_13.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_14.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_15.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_16.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_17.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_18.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_19.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_20.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_21.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_22.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_23.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_24.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_25.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_26.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_27.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_28.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_29.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_30.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_31.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_32.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_33.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_34.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_35.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_36.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_37.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_38.png"),
      require("../../assets/images/Cabellos/Cabello_rojo_39.png"),
    ],
    
    azul: [
        require("../../assets/images/Cabellos/Cabello_azul_01.png"),
        require("../../assets/images/Cabellos/Cabello_azul_02.png"),
        require("../../assets/images/Cabellos/Cabello_azul_03.png"),
        require("../../assets/images/Cabellos/Cabello_azul_04.png"),
        require("../../assets/images/Cabellos/Cabello_azul_05.png"),
        require("../../assets/images/Cabellos/Cabello_azul_06.png"),
        require("../../assets/images/Cabellos/Cabello_azul_07.png"),
        require("../../assets/images/Cabellos/Cabello_azul_08.png"),
        require("../../assets/images/Cabellos/Cabello_azul_09.png"),
        require("../../assets/images/Cabellos/Cabello_azul_10.png"),
        require("../../assets/images/Cabellos/Cabello_azul_11.png"),
        require("../../assets/images/Cabellos/Cabello_azul_12.png"),
        require("../../assets/images/Cabellos/Cabello_azul_13.png"),
        require("../../assets/images/Cabellos/Cabello_azul_14.png"),
        require("../../assets/images/Cabellos/Cabello_azul_15.png"),
        require("../../assets/images/Cabellos/Cabello_azul_16.png"),
        require("../../assets/images/Cabellos/Cabello_azul_17.png"),
        require("../../assets/images/Cabellos/Cabello_azul_18.png"),
        require("../../assets/images/Cabellos/Cabello_azul_19.png"),
        require("../../assets/images/Cabellos/Cabello_azul_20.png"),
        require("../../assets/images/Cabellos/Cabello_azul_21.png"),
        require("../../assets/images/Cabellos/Cabello_azul_22.png"),
        require("../../assets/images/Cabellos/Cabello_azul_23.png"),
        require("../../assets/images/Cabellos/Cabello_azul_24.png"),
        require("../../assets/images/Cabellos/Cabello_azul_25.png"),
        require("../../assets/images/Cabellos/Cabello_azul_26.png"),
        require("../../assets/images/Cabellos/Cabello_azul_27.png"),
        require("../../assets/images/Cabellos/Cabello_azul_28.png"),
        require("../../assets/images/Cabellos/Cabello_azul_29.png"),
        require("../../assets/images/Cabellos/Cabello_azul_30.png"),
        require("../../assets/images/Cabellos/Cabello_azul_31.png"),
        require("../../assets/images/Cabellos/Cabello_azul_32.png"),
        require("../../assets/images/Cabellos/Cabello_azul_33.png"),
        require("../../assets/images/Cabellos/Cabello_azul_34.png"),
        require("../../assets/images/Cabellos/Cabello_azul_35.png"),
        require("../../assets/images/Cabellos/Cabello_azul_36.png"),
        require("../../assets/images/Cabellos/Cabello_azul_37.png"),
        require("../../assets/images/Cabellos/Cabello_azul_38.png"),
        require("../../assets/images/Cabellos/Cabello_azul_39.png"),
        require("../../assets/images/Cabellos/Cabello_azul_40.png"),
      ],
      cafe: [
        require("../../assets/images/Cabellos/Cabello_cafes_01.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_02.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_03.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_04.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_05.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_06.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_07.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_08.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_09.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_10.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_11.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_12.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_13.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_14.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_15.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_16.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_17.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_18.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_19.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_20.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_21.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_22.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_23.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_24.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_25.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_26.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_27.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_28.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_29.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_30.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_31.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_32.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_33.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_34.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_35.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_36.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_37.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_38.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_39.png"),
        require("../../assets/images/Cabellos/Cabello_cafes_40.png"),
      ],
      
      marron: [
        require("../../assets/images/Cabellos/Cabello_marron_01.png"),
        require("../../assets/images/Cabellos/Cabello_marron_02.png"),
        require("../../assets/images/Cabellos/Cabello_marron_03.png"),
        require("../../assets/images/Cabellos/Cabello_marron_04.png"),
        require("../../assets/images/Cabellos/Cabello_marron_05.png"),
        require("../../assets/images/Cabellos/Cabello_marron_06.png"),
        require("../../assets/images/Cabellos/Cabello_marron_07.png"),
        require("../../assets/images/Cabellos/Cabello_marron_08.png"),
        require("../../assets/images/Cabellos/Cabello_marron_09.png"),
        require("../../assets/images/Cabellos/Cabello_marron_10.png"),
        require("../../assets/images/Cabellos/Cabello_marron_11.png"),
        require("../../assets/images/Cabellos/Cabello_marron_12.png"),
        require("../../assets/images/Cabellos/Cabello_marron_13.png"),
        require("../../assets/images/Cabellos/Cabello_marron_14.png"),
        require("../../assets/images/Cabellos/Cabello_marron_15.png"),
        require("../../assets/images/Cabellos/Cabello_marron_16.png"),
        require("../../assets/images/Cabellos/Cabello_marron_17.png"),
        require("../../assets/images/Cabellos/Cabello_marron_18.png"),
        require("../../assets/images/Cabellos/Cabello_marron_19.png"),
        require("../../assets/images/Cabellos/Cabello_marron_20.png"),
        require("../../assets/images/Cabellos/Cabello_marron_21.png"),
        require("../../assets/images/Cabellos/Cabello_marron_22.png"),
        require("../../assets/images/Cabellos/Cabello_marron_23.png"),
        require("../../assets/images/Cabellos/Cabello_marron_24.png"),
        require("../../assets/images/Cabellos/Cabello_marron_25.png"),
        require("../../assets/images/Cabellos/Cabello_marron_26.png"),
        require("../../assets/images/Cabellos/Cabello_marron_27.png"),
        require("../../assets/images/Cabellos/Cabello_marron_28.png"),
        require("../../assets/images/Cabellos/Cabello_marron_29.png"),
        require("../../assets/images/Cabellos/Cabello_marron_30.png"),
        require("../../assets/images/Cabellos/Cabello_marron_31.png"),
        require("../../assets/images/Cabellos/Cabello_marron_32.png"),
        require("../../assets/images/Cabellos/Cabello_marron_33.png"),
        require("../../assets/images/Cabellos/Cabello_marron_34.png"),
        require("../../assets/images/Cabellos/Cabello_marron_35.png"),
        require("../../assets/images/Cabellos/Cabello_marron_36.png"),
        require("../../assets/images/Cabellos/Cabello_marron_37.png"),
        require("../../assets/images/Cabellos/Cabello_marron_38.png"),
        require("../../assets/images/Cabellos/Cabello_marron_39.png"),
        require("../../assets/images/Cabellos/Cabello_marron_40.png"),
      ],
      naranja: [
        require("../../assets/images/Cabellos/Cabello_naranja_01.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_02.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_03.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_04.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_05.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_06.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_07.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_08.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_09.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_10.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_11.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_12.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_13.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_14.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_15.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_16.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_17.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_18.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_19.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_20.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_21.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_22.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_23.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_24.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_25.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_26.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_27.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_28.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_29.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_30.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_31.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_32.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_33.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_34.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_35.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_36.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_37.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_38.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_39.png"),
        require("../../assets/images/Cabellos/Cabello_naranja_40.png"),
      ],
      
      blanco: [
        require("../../assets/images/Cabellos/Cabello_blanco_01.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_02.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_03.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_04.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_05.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_06.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_07.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_08.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_09.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_10.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_11.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_12.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_13.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_14.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_15.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_16.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_17.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_18.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_19.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_20.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_21.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_22.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_23.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_24.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_25.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_26.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_27.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_28.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_29.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_30.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_31.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_32.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_33.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_34.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_35.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_36.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_37.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_38.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_39.png"),
        require("../../assets/images/Cabellos/Cabello_blanco_40.png"),
      ],
      wero: [
        require("../../assets/images/Cabellos/Cabello_wero_01.png"),
        require("../../assets/images/Cabellos/Cabello_wero_02.png"),
        require("../../assets/images/Cabellos/Cabello_wero_03.png"),
        require("../../assets/images/Cabellos/Cabello_wero_04.png"),
        require("../../assets/images/Cabellos/Cabello_wero_05.png"),
        require("../../assets/images/Cabellos/Cabello_wero_06.png"),
        require("../../assets/images/Cabellos/Cabello_wero_07.png"),
        require("../../assets/images/Cabellos/Cabello_wero_08.png"),
        require("../../assets/images/Cabellos/Cabello_wero_09.png"),
        require("../../assets/images/Cabellos/Cabello_wero_10.png"),
        require("../../assets/images/Cabellos/Cabello_wero_11.png"),
        require("../../assets/images/Cabellos/Cabello_wero_12.png"),
        require("../../assets/images/Cabellos/Cabello_wero_13.png"),
        require("../../assets/images/Cabellos/Cabello_wero_14.png"),
        require("../../assets/images/Cabellos/Cabello_wero_15.png"),
        require("../../assets/images/Cabellos/Cabello_wero_16.png"),
        require("../../assets/images/Cabellos/Cabello_wero_17.png"),
        require("../../assets/images/Cabellos/Cabello_wero_18.png"),
        require("../../assets/images/Cabellos/Cabello_wero_19.png"),
        require("../../assets/images/Cabellos/Cabello_wero_20.png"),
        require("../../assets/images/Cabellos/Cabello_wero_21.png"),
        require("../../assets/images/Cabellos/Cabello_wero_22.png"),
        require("../../assets/images/Cabellos/Cabello_wero_23.png"),
        require("../../assets/images/Cabellos/Cabello_wero_24.png"),
        require("../../assets/images/Cabellos/Cabello_wero_25.png"),
        require("../../assets/images/Cabellos/Cabello_wero_26.png"),
        require("../../assets/images/Cabellos/Cabello_wero_27.png"),
        require("../../assets/images/Cabellos/Cabello_wero_28.png"),
        require("../../assets/images/Cabellos/Cabello_wero_29.png"),
        require("../../assets/images/Cabellos/Cabello_wero_30.png"),
        require("../../assets/images/Cabellos/Cabello_wero_31.png"),
        require("../../assets/images/Cabellos/Cabello_wero_32.png"),
        require("../../assets/images/Cabellos/Cabello_wero_33.png"),
        require("../../assets/images/Cabellos/Cabello_wero_34.png"),
        require("../../assets/images/Cabellos/Cabello_wero_35.png"),
        require("../../assets/images/Cabellos/Cabello_wero_36.png"),
        require("../../assets/images/Cabellos/Cabello_wero_37.png"),
        require("../../assets/images/Cabellos/Cabello_wero_38.png"),
        require("../../assets/images/Cabellos/Cabello_wero_39.png"),
        require("../../assets/images/Cabellos/Cabello_wero_40.png"),
      ],

      verde: [
        require("../../assets/images/Cabellos/Cabello_verde_01.png"),
        require("../../assets/images/Cabellos/Cabello_verde_02.png"),
        require("../../assets/images/Cabellos/Cabello_verde_03.png"),
        require("../../assets/images/Cabellos/Cabello_verde_04.png"),
        require("../../assets/images/Cabellos/Cabello_verde_05.png"),
        require("../../assets/images/Cabellos/Cabello_verde_06.png"),
        require("../../assets/images/Cabellos/Cabello_verde_07.png"),
        require("../../assets/images/Cabellos/Cabello_verde_08.png"),
        require("../../assets/images/Cabellos/Cabello_verde_09.png"),
        require("../../assets/images/Cabellos/Cabello_verde_10.png"),
        require("../../assets/images/Cabellos/Cabello_verde_11.png"),
        require("../../assets/images/Cabellos/Cabello_verde_12.png"),
        require("../../assets/images/Cabellos/Cabello_verde_13.png"),
        require("../../assets/images/Cabellos/Cabello_verde_14.png"),
        require("../../assets/images/Cabellos/Cabello_verde_15.png"),
        require("../../assets/images/Cabellos/Cabello_verde_16.png"),
        require("../../assets/images/Cabellos/Cabello_verde_17.png"),
        require("../../assets/images/Cabellos/Cabello_verde_18.png"),
        require("../../assets/images/Cabellos/Cabello_verde_19.png"),
        require("../../assets/images/Cabellos/Cabello_verde_20.png"),
        require("../../assets/images/Cabellos/Cabello_verde_21.png"),
        require("../../assets/images/Cabellos/Cabello_verde_22.png"),
        require("../../assets/images/Cabellos/Cabello_verde_23.png"),
        require("../../assets/images/Cabellos/Cabello_verde_24.png"),
        require("../../assets/images/Cabellos/Cabello_verde_25.png"),
        require("../../assets/images/Cabellos/Cabello_verde_26.png"),
        require("../../assets/images/Cabellos/Cabello_verde_27.png"),
        require("../../assets/images/Cabellos/Cabello_verde_28.png"),
        require("../../assets/images/Cabellos/Cabello_verde_29.png"),
        require("../../assets/images/Cabellos/Cabello_verde_30.png"),
        require("../../assets/images/Cabellos/Cabello_verde_31.png"),
        require("../../assets/images/Cabellos/Cabello_verde_32.png"),
        require("../../assets/images/Cabellos/Cabello_verde_33.png"),
        require("../../assets/images/Cabellos/Cabello_verde_34.png"),
        require("../../assets/images/Cabellos/Cabello_verde_35.png"),
        require("../../assets/images/Cabellos/Cabello_verde_36.png"),
        require("../../assets/images/Cabellos/Cabello_verde_37.png"),
        require("../../assets/images/Cabellos/Cabello_verde_38.png"),
        require("../../assets/images/Cabellos/Cabello_verde_39.png"),
        require("../../assets/images/Cabellos/Cabello_verde_40.png"),
      ],

      rosa: [
        require("../../assets/images/Cabellos/Cabello_rosa_01.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_02.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_03.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_04.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_05.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_06.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_07.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_08.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_09.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_10.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_11.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_12.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_13.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_14.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_15.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_16.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_17.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_18.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_19.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_20.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_21.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_22.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_23.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_24.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_25.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_26.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_27.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_28.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_29.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_30.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_31.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_32.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_33.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_34.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_35.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_36.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_37.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_38.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_39.png"),
        require("../../assets/images/Cabellos/Cabello_rosa_40.png"),
      ],
      morrado: [
        require("../../assets/images/Cabellos/Cabello_morrado_01.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_02.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_03.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_04.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_05.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_06.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_07.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_08.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_09.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_10.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_11.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_12.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_13.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_14.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_15.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_16.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_17.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_18.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_19.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_20.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_21.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_22.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_23.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_24.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_25.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_26.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_27.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_28.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_29.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_30.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_31.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_32.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_33.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_34.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_35.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_36.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_37.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_38.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_39.png"),
        require("../../assets/images/Cabellos/Cabello_morrado_40.png"),
      ],
       
  }

  const handleColorChange = (color) => {
    setColorSeleccionado(color)
    setImagenSeleccionada(null)
  }

  const handleImagePress = (imagen) => {
    if (imagenSeleccionada === imagen) {
      setImagenSeleccionada(null)
      onSelect(null, "Cabellos")
    } else {
      setImagenSeleccionada(imagen)
      onSelect(imagen, "Cabellos")
    }
  }

  const ImageCard = ({ imagen }) => (
    <TouchableOpacity onPress={() => handleImagePress(imagen)}>
      <View style={styles.cardContainer}>
        <ImageBackground
          source={require("../../assets/images/otras/fondo_items.png")}
          style={styles.card}
          resizeMode="cover"
        >
          <Image source={imagen} style={styles.image} />
        </ImageBackground>
        {imagenSeleccionada === imagen && <View style={styles.selectionOverlay} />}
      </View>
    </TouchableOpacity>
  )

  const ColorButton = ({ color, activeColor, inactiveColor }) => (
    <TouchableOpacity
      style={[
        styles.circleButton,
        { borderColor: inactiveColor },
        colorSeleccionado === color && { backgroundColor: activeColor, borderColor: inactiveColor },
      ]}
      onPress={() => handleColorChange(color)}
    />
  )

  return (
    <ImageBackground source={require("../../assets/images/otras/fondo_elementos.png")} style={styles.container}>
      <View style={styles.buttonsContainer}>
        <ColorButton color="negro" activeColor="#3b3436" inactiveColor="#191717" />
        <ColorButton color="rojo" activeColor="#a92847" inactiveColor="#950628" />
        <ColorButton color="cafe" activeColor="#c18300" inactiveColor="#bc9440" />
        <ColorButton color="marron" activeColor="#5b3c11" inactiveColor="#281802" />
        <ColorButton color="naranja" activeColor="#e46c2c" inactiveColor="#c44500" />
        <ColorButton color="blanco" activeColor="#ffffff" inactiveColor="#d3d3d3" />
        <ColorButton color="wero" activeColor="#faf3a2" inactiveColor="#d6b46c" />
        <ColorButton color="azul" activeColor="#0190d8" inactiveColor="#00598d" />
        <ColorButton color="verde" activeColor="#4b975a" inactiveColor="#255e24" />
        <ColorButton color="rosa" activeColor="#d665ac" inactiveColor="#8c1658" />
        <ColorButton color="morrado" activeColor="#7c41ae" inactiveColor="#5e1a87" />
      </View>

      <View style={styles.safeContainer}>
        <ScrollView style={styles.scrollContainer} contentContainerStyle={styles.imagesScrollContainer}>
          <View style={styles.imagesContainer}>
            {imagenesPorColor[colorSeleccionado]?.map((imagen, index) => (
              <ImageCard key={index} imagen={imagen} />
            ))}
          </View>
        </ScrollView>
      </View>
    </ImageBackground>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeContainer: {
    paddingTop: 50,
    flex: 1,
  },
  buttonsContainer: {
    flexDirection: 'row',
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 1,
  },
  circleButton: {
    width: 25,
    height: 25,
    borderRadius: 12.5,
    marginLeft: 5,
    borderWidth: 3,
    backgroundColor: 'transparent',
  },
  scrollContainer: {
    flex: 1,
    maxHeight: 300,
  },
  imagesScrollContainer: {
    paddingTop: 10,
    paddingBottom: 20,
  },
  imagesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: 20,
  },
  cardContainer: {
    position: "relative",
    width: 75,
    height: 75,
    margin: 5,
  },
  card: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    overflow: "hidden",
  },
  image: {
    width: 75,
    height: 75,
    resizeMode: "contain",
  },
  selectionOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#d0e8f2",
    opacity: 0.5,
    borderRadius: 10,
    borderColor: "#007d7d",
    borderWidth: 2,
  },
})

export default Cabellos

